# Generated by Django 5.2 on 2025-04-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('idurunler', models.IntegerField(primary_key=True, serialize=False)),
                ('barkod', models.CharField(max_length=45)),
                ('stok_kodu', models.CharField(blank=True, max_length=45, null=True)),
                ('urun_detayi', models.CharField(max_length=45)),
                ('birim', models.CharField(max_length=45)),
                ('miktar', models.IntegerField()),
                ('alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ikincil_birim', models.CharField(blank=True, max_length=45, null=True)),
                ('birim_basi_miktar', models.IntegerField(blank=True, null=True)),
                ('ikincil_alis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ikicil_satis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
