# Generated by Django 5.2 on 2025-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='ikicil_satis_fiyati',
            new_name='ikincil_satis_fiyati',
        ),
        migrations.AlterField(
            model_name='urun',
            name='idurunler',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
