# Generated by Django 5.2 on 2025-05-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_rename_ikicil_satis_fiyati_urun_ikincil_satis_fiyati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.kategori'),
        ),
    ]
