# Generated by Django 5.2 on 2025-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_kategori_urun_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kategori_resimleri/'),
        ),
        migrations.AddField(
            model_name='urun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='urun_resimleri/'),
        ),
    ]
