# Generated by Django 5.2 on 2025-05-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_kategori_image_urun_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='isim',
            new_name='ad',
        ),
    ]
