# Generated by Django 5.2 on 2025-05-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_rename_isim_kategori_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='idurunler',
            new_name='id',
        ),
    ]
